name: test

on:
  push:
  pull_request:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]
        python-version:
        - "3.7"
        - "3.8"
        - "3.9"
        - "3.12-dev"
        - "3.11"
    
    name: Test
    runs-on: ${{matrix.os}}
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version}}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install coverage

    - name: Run Test
      run: pytest

    - name: Generate Coverage Report  
      run: |  
        coverage report -m
